[0;33m--- esp-idf-monitor 1.3.4 on /dev/cu.usbserial-DU0CUKCC 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x420087d8: i2c_init at /Users/naichenzhao/Desktop/SLICE/SLICE-Spider/Firmware/V1/spider_main/main/i2c.c:41 (discriminator 1)
[0m
[0;33m0x4080503b: _esp_error_check_failed at /Users/naichenzhao/esp/esp-idf/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x408007c0: panic_abort at /Users/naichenzhao/esp/esp-idf/components/esp_system/panic.c:472
[0m
[0;33m0x40805046: __ubsan_include at /Users/naichenzhao/esp/esp-idf/components/esp_system/ubsan.c:313
[0m
[0;33m0x4080618c: uxInitialiseStackFrame at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:352
 (inlined by) pxPortInitialiseStack at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:425
[0m
[0;33m0x40800001: _vector_table at ??:?
[0m
[1;31mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/Users/naichenzhao/Desktop/SLICE/SLICE-Spider/Firmware/V1/spider_main/build/app-template.elf', '-ex', 'target remote | "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/bin/python" -m "esp_idf_panic_decoder" --target esp32c6 "/var/folders/2h/lww79zv53b510qlyvytqnvq40000gn/T/tmp5d44ojr1"', '-ex', 'bt']' returned non-zero exit status 1.
b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n  File "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 281, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/naichenzhao/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 134, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote connection closed\nNo stack.\n'

[0m
[0;33m0x4001975a: software_reset_cpu in ROM
[0m
[0;33m0x420087d8: i2c_init at /Users/naichenzhao/Desktop/SLICE/SLICE-Spider/Firmware/V1/spider_main/main/i2c.c:41 (discriminator 1)
[0m
[0;33m0x4080503b: _esp_error_check_failed at /Users/naichenzhao/esp/esp-idf/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x408007c0: panic_abort at /Users/naichenzhao/esp/esp-idf/components/esp_system/panic.c:472
[0m
[0;33m0x40805046: __ubsan_include at /Users/naichenzhao/esp/esp-idf/components/esp_system/ubsan.c:313
[0m
[0;33m0x4080618c: uxInitialiseStackFrame at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:352
 (inlined by) pxPortInitialiseStack at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:425
[0m
[0;33m0x40800001: _vector_table at ??:?
[0m
[0;33m
Backtrace:

[0m
[0;33m0x4001975a: software_reset_cpu in ROM
[0m
[0;33m0x420087d8: i2c_init at /Users/naichenzhao/Desktop/SLICE/SLICE-Spider/Firmware/V1/spider_main/main/i2c.c:41 (discriminator 1)
[0m
[0;33m0x4080503b: _esp_error_check_failed at /Users/naichenzhao/esp/esp-idf/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x408007c0: panic_abort at /Users/naichenzhao/esp/esp-idf/components/esp_system/panic.c:472
[0m
[0;33m0x40805046: __ubsan_include at /Users/naichenzhao/esp/esp-idf/components/esp_system/ubsan.c:313
[0m
[0;33m0x4080618c: uxInitialiseStackFrame at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:352
 (inlined by) pxPortInitialiseStack at /Users/naichenzhao/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:425
[0m
[0;33m0x40800001: _vector_table at ??:?
[0m
[0;33m
Backtrace:

[0m
[0;33m0x4001975a: software_reset_cpu in ROM
[0m
[0m
